from collections.abc import Generator, Iterable, Mapping
from pathlib import Path
from typing import Any, TextIO

from _typeshed import Incomplete
from requests.structures import CaseInsensitiveDict

__all__ = ['ReadStructure', 'Sample', 'SampleSheet']

class ReadStructure:
    structure: Incomplete
    def __init__(self, structure: str) -> None: ...
    @property
    def is_indexed(self) -> bool: ...
    @property
    def is_single_indexed(self) -> bool: ...
    @property
    def is_dual_indexed(self) -> bool: ...
    @property
    def is_single_end(self) -> bool: ...
    @property
    def is_paired_end(self) -> bool: ...
    @property
    def has_indexes(self) -> bool: ...
    @property
    def has_skips(self) -> bool: ...
    @property
    def has_umi(self) -> bool: ...
    @property
    def index_cycles(self) -> int: ...
    @property
    def template_cycles(self) -> int: ...
    @property
    def skip_cycles(self) -> int: ...
    @property
    def umi_cycles(self) -> int: ...
    @property
    def total_cycles(self) -> int: ...
    @property
    def tokens(self) -> list[str]: ...
    @property
    def index_tokens(self) -> list[str]: ...
    @property
    def skip_tokens(self) -> list[str]: ...
    @property
    def template_tokens(self) -> list[str]: ...
    @property
    def umi_tokens(self) -> list[str]: ...
    def copy(self) -> ReadStructure: ...
    def __eq__(self, other: object) -> bool: ...

class Sample(CaseInsensitiveDict):
    sample_sheet: SampleSheet | None
    def __init__(self, data: Mapping | None = None, **kwargs: Mapping) -> None: ...
    def to_json(self) -> Mapping: ...
    def __eq__(self, other: object) -> bool: ...
    def __getattr__(self, attr: Any) -> Any | None: ...

class Section(CaseInsensitiveDict):
    def __init__(self, data: Mapping | None = None, **kwargs: Mapping) -> None: ...
    def __getattr__(self, attr: Any) -> Any | None: ...

class SampleSheet:
    path: Incomplete
    Reads: list[int]
    Read_Structure: ReadStructure | None
    samples_have_index: bool | None
    samples_have_index2: bool | None
    Header: Section
    Settings: Section
    def __init__(self, path: Path | str | TextIO | None = None) -> None: ...
    def add_section(self, section_name: str) -> None: ...
    @property
    def all_sample_keys(self) -> list[str]: ...
    @property
    def experimental_design(self) -> Any: ...
    @property
    def is_paired_end(self) -> bool | None: ...
    @property
    def is_single_end(self) -> bool | None: ...
    @property
    def samples(self) -> list: ...
    def add_sample(self, sample: Sample) -> None: ...
    def add_samples(self, samples: Iterable[Sample]) -> None: ...
    def to_json(self, **kwargs: Mapping) -> str: ...
    def to_picard_basecalling_params(self, directory: str | Path, bam_prefix: str | Path, lanes: int | list[int]) -> None: ...
    def write(self, handle: TextIO, blank_lines: int = 1) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Generator[Sample]: ...
